return {
	BufferVisible = 'Overlay',
	BufferVisibleMod = { fg = 'Red', bg = 'Overlay', italic = true },
	BufferVisibleSign = { fg = 'Magenta', bg = 'Overlay' },
	BufferCurrent = 'Bold',
	BufferCurrentMod = { fg = 'LightRed', bold = true, italic = true },
	BufferCurrentSign = 'LightGreen',
	BufferInactive = { fg = 'Fg3', bg = 'Overlay' },
	BufferInactiveMod = { fg = 'LightOrange', bg = 'Overlay', italic = true },
	BufferInactiveSign = 'BufferInactive',
	BufferTabpages = { fg = 'Cyan', bg = 'Overlay' },
	BufferTabpageFill = { fg = 'Fg4', bg = 'Overlay' },
	BufferTabpagesSep = 'Overlay',
	BufferScrollArrow = 'Overlay',
}
