return {
	BufferCurrent = 'Bold',
	BufferCurrentMod = { fg = 'LightRed', bold = true, italic = true },
	BufferCurrentSign = 'Ac1',
	BufferVisible = 'WinBar',
	BufferVisibleMod = { fg = 'Red', bg = 'WinBar', italic = true },
	BufferVisibleSign = { fg = 'Ac2', bg = 'WinBar' },
	BufferInactive = { fg = 'Fg3', bg = 'WinBar' },
	BufferInactiveMod = { fg = 'LightOrange', bg = 'WinBar', italic = true },
	BufferInactiveSign = 'BufferInactive',
	BufferTabpages = { fg = 'Fg5', bg = 'WinBar' },
	BufferTabpageFill = { fg = 'Fg5', bg = 'WinBar' },
	BufferTabpagesSep = 'WinBar',
	BufferScrollArrow = 'WinBar',
}
