return {
	BufferVisible = "Fg0",
	BufferVisibleMod = "LightRed",
	BufferVisibleSign = "LightMagenta",
	BufferCurrent = {{fg = "Fg0"}, {bold = true}},
	BufferCurrentMod = {fg = "LightRed", bold = true},
	BufferCurrentSign = "LightGreen",
	BufferInactive = "Fg2",
	BufferInactiveMod = "Orange",
	BufferInactiveSign = "Fg2",
	BufferTabpages = "Cyan",
	BufferTabpageFill = "Fg4",
	BufferScrollArrow = "Bg1",
	BufferTabpagesSep = "",
}
