return {
	BufferVisible = "Overlay",
	BufferVisibleMod = {fg = "Red", bg = "Overlay", {}},
	BufferVisibleSign = {fg = "LightMagenta", bg = "Overlay", {}},
	BufferCurrent = {fg = "Fg1", bg = "OverlaySel", {bold = true}},
	BufferCurrentMod = {fg = "LightRed", bg = "OverlaySel", {bold = true}},
	BufferCurrentSign = {fg = "LightGreen", bg = "OverlaySel", {}},
	BufferInactive = {fg = "Fg3", bg = "Overlay", {}},
	BufferInactiveMod = {fg = "Orange", bg = "Overlay", {}},
	BufferInactiveSign = {fg = "Fg3", bg = "Overlay", {}},
	BufferTabpages = {fg = "Cyan", bg = "Overlay", {}},
	BufferTabpageFill = {fg = "Fg4", bg = "Overlay", {}},
	BufferTabpagesSep = "Overlay",
	BufferScrollArrow = "Overlay",
}
