return {
	CmpItemAbbrMatch = "LightBlue",
	CmpItemKind = "Delimiter",
	CmpItemKindText = "String",
	CmpItemKindKeyword = "Keyword",
	CmpItemKindFunction = "Command",
	CmpItemKindMethod = "CmpItemKindFunction",
	CmpItemKindField = "@field",
	CmpItemKindVariable = "Variable",
	CmpItemKindEnum = "Constant",
	CmpItemKindEnumMember = "Constant",
	CmpItemKindConstant = "Constant",
	CmpItemKindProperty = "@field",
	CmpItemKindUnit = "Number",
	CmpItemKindValue = "Normal",
	CmpItemKindFile = "Brown",
	CmpItemKindFolder = "Brown",
	CmpItemKindOperator = "Operator",
	CmpItemKindSnippet = "Macro",
	CmpItemKindConstructor = "CmpItemKindMethod",
	CmpItemKindClass = "Pink",
	CmpItemKindTable = "LightCyan",
	CmpItemKindStruct = "CmpItemKindTable",
	CmpItemKindInterface = "CmpItemKindClass",
}
