return {
	DapUIStop = "LightRed",
	DapUIRestart = "LightRed",
	DapUIStepOver = "Green",
	DapUIStepInto = "Green",
	DapUIStepOut = "LightYellow",
	DapUIStepBack = "LightMagenta",
	DapUIPlayPause = "LightOrange",
	DapUIUnavailable = "Fg3",
	DapUIThread = "Fg1",
	DapUICurrentFrameName = {fg = "Contrast", underline = true},
	DapUIFrameName = "Fg3",
	DapUIFloatBorder = "FloatBorder",
	DapUILineNumber = "LineNr",
	DapUIStoppedThread = "Orange",
	DapUIBreakpointsCurrentLine = "DiagnosticSignInfo",
	DapUIBreakpointsLine = "Red",
	DapUIBreakpointsInfo = "Red",
	DapUIBreakpointsPath = "Brown",
	DapUIWatchesEmpty = "Red",
	DapUIWatchesError = "Red",
	DapUIModifiedValue = "Cyan",
	DapUIType = "Keyword",
	DapUIVariable = "Variable",
	DapUISource = "Brown",
	DapUIScope = "Contrast",
	DapUIWatchesValue = "Fg1",
	DapUIValue = "Fg1",
	DapUIDecoration = "Fg1",
}
