return {
	DapUIStop = "LightRed",
	DapUIRestart = "LightRed",
	DapUIStepOver = "Green",
	DapUIStepInto = "Green",
	DapUIStepOut = "LightYellow",
	DapUIStepBack = "LightMagenta",
	DapUIPlayPause = "LightOrange",
	DapUIUnavailable = "Fg2",
	DapUIThread = "Fg0",
	DapUICurrentFrameName = {fg = "Magenta", underline = true},
	DapUIFrameName = "Fg2",
	DapUIFloatBorder = "FloatBorder",
	DapUILineNumber = "LineNr",
	DapUIStoppedThread = "Orange",
	DapUIBreakpointsCurrentLine = "DiagnosticSignInfo",
	DapUIBreakpointsLine = "Red",
	DapUIBreakpointsInfo = "Red",
	DapUIBreakpointsPath = "Brown",
	DapUIWatchesEmpty = "Red",
	DapUIWatchesError = "Red",
	DapUIModifiedValue = "Cyan",
	DapUIType = "Keyword",
	DapUIVariable = "Variable",
	DapUISource = "Brown",
	DapUIScope = "Magenta",
	DapUIWatchesValue = "Fg0",
	DapUIValue = "Fg0",
	DapUIDecoration = "Fg0",
}
