return {
	FzfLuaBorder = 'FloatBorder',
	FzfLuaTitle = 'FloatTitle',
	FzfLuaSearch = 'Search',
	FzfLuaCursor = { reverse = true },
	FzfLuaCursorLine = { bg = 'CursorLine', underline = true },
	FzfLuaHeaderBind = 'SpecialKey',
	FzfLuaHeaderText = 'Comment',
	FzfLuaBufFlagCur = 'Special',
	FzfLuaBufFlagAlt = 'Special',
	FzfLuaBufNr = 'Operator',
	FzfLuaBufName = 'Ac2',
	FzfLuaPathColNr = 'Number',
	FzfLuaPathLineNr = 'Number',
}
