return {
	LazyNormal = 'Pmenu',
	LazyButton = 'PmenuSel',
	LazyH2 = 'Title',
	LazyButtonActive = { bg = 'Bg3', bold = true },
	LazyCommit = 'String',
	LazyH3 = 'LightGreen',
	LazyReasonStart = 'Title',
	LazyReasonPlugin = 'Magenta',
	LazyReasonEvent = 'PreProc',
	LazyReasonFt = 'String',
	LazyReasonCmd = 'Statement',
	LazyReasonSource = 'Orange',
	LazyReasonImport = 'Parameter',
	LazyReasonKeys = 'SpecialKey',
	LazySpecial = 'Delimiter',
	LazyDimmed = 'Fg4',
	LazyProp = 'LightOrange',
}
