return {
	LazyNormal = "Bg1",
	LazyButton = "Bg2",
	LazyH1 = {bg = "Bg3", bold = true},
	LazyButtonActive = "LazyH1",
	LazyCommit = "String",
	LazyH2 = "Title",
	LazyReasonStart = "Title",
	LazyReasonPlugin = "LightMagenta",
	LazyReasonEvent = "PreProc",
	LazyReasonFt = "String",
	LazyReasonCmd = "Command",
	LazyReasonSource = "Brown",
	LazyReasonImport = "Parameter",
	LazyReasonKeys = "SpecialKey",
	LazySpecial = "Delimiter",
	LazyDimmed = "Fg4",
	LazyProp = "Orange",
}
