return {
	LazyNormal = "Bg2",
	LazyButton = "Bg3",
	LazyH2 = {{bg = "Bg3"}, {bold = true}},
	LazyButtonActive = "LazyH2",
	LazyCommit = "String",
	LazyH3 = "Title",
	LazyReasonStart = "Title",
	LazyReasonPlugin = "LightMagenta",
	LazyReasonEvent = "PreProc",
	LazyReasonFt = "String",
	LazyReasonCmd = "Statement",
	LazyReasonSource = "Brown",
	LazyReasonImport = "Parameter",
	LazyReasonKeys = "SpecialKey",
	LazySpecial = "Delimiter",
	LazyDimmed = "Fg4",
	LazyProp = "Orange",
}
