return {
	['@field'] = 'LightGreen',
	['@namespace'] = 'Cyan',
	['@variable'] = 'Variable',
	['@parameter'] = 'Olive',
	['@constructor'] = 'Type',
	['@environment'] = 'Constant',
	['@attribute'] = '@parameter',
	['@storageclass'] = 'Keyword',
	['@type.builtin'] = { fg = 'FgBlue', italic = true },
	['@constant.builtin'] = 'Boolean',
	['@function.builtin'] = { fg = 'LightBlue', italic = true },
	['@variable.builtin'] = { fg = 'Cyan', italic = true },
	['@property'] = '@field',
	['@string.special'] = 'LightOrange',
	-- Markdown
	['@none'] = '',
	['@text.literal'] = 'Cyan',
	['@text.literal.block'] = 'Fg2',
	['@text.reference'] = 'Url',
	['@text.uri'] = { fg = 'Fg4', underline = true },
	['@text.title'] = 'Title',
	['@text.emphasis'] = 'Italic',
	['@text.strong'] = 'Bold',
	['@text.math'] = 'FgRed',
	['@text.todo.checked.markdown'] = { fg = 'Green', bold = true },
	['@text.title.1.marker'] = { fg = 'LightRed', bold = true },
	['@text.title.2.marker'] = '@text.title.1.marker',
	['@text.title.3.marker'] = 'Delimiter',
	['@text.title.4.marker'] = 'Delimiter',
	['@text.title.5.marker'] = 'Delimiter',
	['@text.title.1'] = { fg = 'LightGreen', bold = true },
	['@text.title.3'] = { fg = 'LightGreen', bold = true, italic = true },
	['@text.title.4'] = 'LightGreen',
	['@text.title.5'] = { fg = 'LightGreen', italic = true },
	-- GitCommit
	['@text.reference.gitcommit'] = 'Variable',
	['@text.uri.gitcommit'] = 'String',
	-- Java
	['@type.qualifier'] = 'Keyword',
	['@attribute.java'] = 'PreProc',
	-- HTML
	['@tag'] = 'Tag',
	['@tag.delimiter'] = 'Delimiter',
	['@tag.attribute'] = '@attribute',
	['@property.css'] = '@attribute',
	-- SQL
	['@type.qualifier.sql'] = 'Conditional',
	['@keyword.operator.sql'] = 'Conditional',
	-- Vim
	['@variable.builtin.vim'] = 'Variable',
	['@string.regex.vim'] = '@string.special',
	['@string.special.vim'] = '@string',
	['@label.vimdoc'] = 'Magenta',
	-- Make
	['@symbol.make'] = 'Variable',
	['@string.make'] = 'Variable',
	['@operator.make'] = 'Delimiter',
	-- Other
	['@type.builtin.kotlin'] = 'Type',
	['@include.c'] = 'PreProc',
	['@include.cpp'] = 'PreProc',
	['@field.yaml'] = 'Variable',
	['@label.json'] = 'Variable',
	['@label.jsonc'] = 'Variable',
	['@namespace.javascript'] = 'Variable',
	['@namespace.typescript'] = 'Variable',
	['@operator.regex'] = '@string.special',
	['@type.query'] = 'Keyword',
	['@constructor.lua'] = 'Delimiter',
	['@keyword.luadoc'] = 'PreProc',
	['@function.macro.luadoc'] = 'Constant',
	['@string.documentation'] = 'Comment',
	['@keyword.jsdoc'] = '@attribute.java',
}
