return {
	NvimTreeNormal = 'WinBar',
	NvimTreeCursorLine = 'WinBarNC',
	NvimTreeIndentMarker = 'Magenta',
	NvimTreeImageFile = 'Yellow',
	NvimTreeGitDirty = 'Orange',
	NvimTreeGitDeleted = 'DiffDelete',
	NvimTreeGitMerge = 'DiffChange',
	NvimTreeGitRenamed = 'DiffChange',
	NvimTreeGitStaged = 'DiffAdd',
	NvimTreeGitNew = 'DiffAdd',
	NvimTreeRootFolder = 'Magenta',
	NvimTreeFolderIcon = 'Green',
	NvimTreeExecFile = { fg = 'LightGreen', bold = true },
	Directory = { fg = 'Green', bold = true },
	NvimTreeSymlink = { fg = 'Cyan', bold = true },
	NvimTreeSpecialFile = 'Fg1',
	NvimTreeOpenedFile = { fg = 'LightOrange', bold = true },
	NvimTreeWindowPicker = { bg = 'Bg2b', bold = true },
}
