return {
	["@field"] = "Field",
	["@namespace"] = "Namespace",
	["@variable"] = "Variable",
	["@parameter"] = "Parameter",
	["@constructor"] = "Type",
	["@keyword.operator"] = "Keyword",
	["@environment"] = "Constant",
	["@attribute"] = "Parameter",
	["@storageclass"] = "Keyword",
	["@type.builtin"] = "Blue",
	["@constant.builtin"] = "Boolean",
	["@function.builtin"] = {fg = "LightBlue", italic= true},
	["@variable.builtin"] = "Namespace",
	["@property"] = "@field",
	["@string.special"] = "Orange",
	-- TreeSitter language highlight changes
	["@text.reference.gitcommit"] = "Variable",
	["@text.uri.gitcommit"] = "String",
	-- Java
	["@type.qualifier"] = "Keyword",
	["@attribute.java"] = "PreProc",
	-- LaTeX
	["@text.environment.latex"] = "Keyword",
	["@text.environment.name.latex"] = "Constant",
	["@text.reference.latex"] = "Title",
	["@text.title"] = "Title",
	["@text.emphasis"] = {italic = true},
	["@text.strong"] = {bold = true},
	["@text.math"] = "Pink",
	["@function.latex"] = "Variable",
	["@error.latex"] = "String",
	["@namespace.latex"] = "Command",
	["@environment.latex"] = "Command",
	-- Markdown
	["@text.literal"] = "Cyan",
	["@text.uri"] = {{fg = "Fg4"}, {italic = true}},
	["@text.reference"] = "Url",
	["@none"] = "Fg1",
	["@text.todo.checked.markdown"] = {fg = "Green", bold = true},
	-- HTML
	["@tag"] = "Statement",
	["@tag.delimiter"] = "Delimiter",
	-- SQL
	["@type.qualifier.sql"] = "Conditional",
	["@keyword.operator.sql"] = "Conditional",
	-- Vim
	["@variable.builtin.vim"] = "Variable",
	["@string.regex.vim"] = "@string.special",
	["@string.special.vim"] = "@string",
	["@label.vimdoc"] = "LightMagenta",
	-- Other
	["@type.builtin.kotlin"] = "Type",
	["@include.c"] = "PreProc",
	["@include.cpp"] = "PreProc",
	["@property.css"] = "Parameter",
	["@tag.attribute.xml"] = "Parameter",
	["@field.yaml"] = "Variable",
	["@label.json"] = "Variable",
	["@none.bash"] = "String",
	["@parameter.bash"] = "Olive",
	["@type.query"] = "Keyword",
	["@constructor.lua"] = "Delimiter",
	["@keyword.luadoc"] = "PreProc",
	["@function.macro.luadoc"] = "Constant",
}
