return {
	NvimTreeNormal = 'WinBar',
	NvimTreeCursorLine = 'WinBarNC',
	NvimTreeIndentMarker = 'Ac1',
	NvimTreeImageFile = 'Yellow',
	NvimTreeGitDirtyIcon = 'Orange',
	NvimTreeGitDeletedIcon = 'DiffDelete',
	NvimTreeGitMergeIcon = 'DiffChange',
	NvimTreeGitRenamedIcon = 'DiffChange',
	NvimTreeGitStagedIcon = 'DiffAdd',
	NvimTreeGitNewIcon = 'DiffAdd',
	NvimTreeRootFolder = 'Ac1',
	NvimTreeFolderIcon = 'Ac2',
	NvimTreeExecFile = 'Bold',
	Directory = { fg = 'Directory', bold = true },
	NvimTreeSymlink = { fg = 'PreProc', bold = true },
	NvimTreeSpecialFile = 'Italic',
	NvimTreeWindowPicker = { bg = 'CursorLine', bold = true },
}
