return {
	NvimTreeOpenedHl = { bg = 'BgAc1', italic = true },
	NvimTreeNormal = 'WinBar',
	NvimTreeCursorLine = 'WinBarNC',
	NvimTreeIndentMarker = 'Ac1',
	NvimTreeImageFile = 'Yellow',
	NvimTreeGitDirtyIcon = 'Orange',
	NvimTreeGitDeletedIcon = 'Removed',
	NvimTreeGitMergeIcon = 'Changed',
	NvimTreeGitRenamedIcon = 'Changed',
	NvimTreeGitStagedIcon = 'Added',
	NvimTreeGitNewIcon = 'Added',
	NvimTreeRootFolder = 'Ac1',
	NvimTreeFolderIcon = 'Ac2',
	NvimTreeExecFile = 'Bold',
	Directory = { fg = 'Directory', bold = true },
	NvimTreeSymlink = { fg = 'PreProc', bold = true },
	NvimTreeSpecialFile = 'Italic',
	NvimTreeWindowPicker = { bg = 'CursorLine', bold = true },
}
