return {
	-- InfoColumn/Cursor
	Visual = 'Bg2b',
	CursorLine = 'Bg2',
	CursorColumn = 'Bg2',
	LineNr = 'Fg4',
	ColorColumn = 'Fg1',
	FoldColumn = 'Fg1',
	SignColumn = 'Fg1',
	CursorLineNr = { fg = 'Fg2', bg = 'Bg2', {} },
	-- Menu elements
	FloatTitle = { fg = 'Olive', bold = true },
	FloatBorder = 'Magenta',
	NormalFloat = 'Fg1',
	Pmenu = 'Bg1b',
	PmenuSel = 'Bg2b',
	PmenuSbar = 'Bg2',
	PmenuThumb = 'Bg3',
	VertSplit = 'Fg4',
	TabLineFill = {},
	TabLineSel = 'Fg1',
	StatusLine = 'Bg2',
	StatusLineNC = 'Bg3',
	Search = { fg = 'LightMagenta', bold = true },
	Substitute = { fg = 'LightOrange', bold = true, reverse = true },
	IncSearch = { fg = 'LightCyan', bold = true },
	Folded = { bg = 'Bg2', { italic = true } },
	MatchParen = { fg = 'LightYellow', italic = true, bold = true },
	Conceal = { fg = 'Orange', bg = 'Bg4', {} },
	NonText = { fg = 'Bg5', {} }, -- used for listchars (indent)
	SpecialKey = 'Orange',
	-- Messages
	ErrorMsg = { fg = 'LightRed', bold = true },
	WarningMsg = { fg = 'LightOrange', bold = true },
	Question = { fg = 'LightYellow', bold = true },
	Error = { sp = 'LightRed', undercurl = true },
	-- Code
	Title = { fg = 'LightGreen', bold = true },
	Todo = { fg = 'Bg2', bg = 'Magenta', { bold = true } },
	Underlined = { fg = 'Fg3', { underline = true } },
	Bold = { bold = true },
	Comment = { fg = 'Fg4', { italic = true } },
	Keyword = 'Blue',
	Tag = 'Keyword',
	Include = 'Keyword',
	Boolean = { fg = 'Blue', italic = true },
	PreProc = 'Cyan',
	Define = 'PreProc',
	Statement = 'LightBlue',
	Label = 'Keyword',
	Exception = 'Keyword',
	Special = 'Magenta',
	SpecialChar = 'Orange',
	Delimiter = 'LightRed',
	Operator = 'Red',
	String = 'Yellow',
	Character = 'LightYellow',
	Number = 'LightPink',
	Identifier = 'Fg1',
	Type = 'Slate',
	TypeDef = { bold = true },
	Function = 'Fg1',
	Constant = { fg = 'Magenta', italic = true },
	Variable = 'Green',
}
