return {
	-- InfoColumn/Cursor
	FoldColumn = "Fg1",
	SignColumn = "Fg1",
	CursorLine = "BgHi",
	CursorColumn = "BgHi",
	LineNr = "Fg4",
	CursorLineNr = {{fg = "Fg3", bg = "BgHi"}},
	-- Menu elements
	FloatTitle = {fg = "Olive", bold = true},
	FloatBorder = "Magenta",
	NormalFloat = "Fg1",
	Pmenu = "Bg2",
	PmenuSel = "Bg3",
	PmenuSbar = "Bg3",
	PmenuThumb = "Bg4",
	VertSplit = "Fg4",
	TabLineFill = "",
	TabLineSel = "Fg1",
	StatusLine = "Bg2",
	StatusLineNC = "Bg3",
	Visual = "Bg2",
	Search = {fg = "LightMagenta", bold = true},
	IncSearch = {fg = "LightBlue", bold = true},
	Folded = {{bg = "Bg2"}, {italic = true}},
	MatchParen = {fg = "LightYellow", italic = true, bold = true},
	Conceal = {{fg = "Orange", bg = "Bg4"}},
	NonText = {{fg = "Bg3"}}, -- used for listchars (indent)
	SpecialKey = "Orange",
	-- Messages
	ErrorMsg = {fg = "LightRed", bold = true},
	WarningMsg = {fg = "LightOrange", bold = true},
	Question = {fg = "LightYellow", bold = true},
	Error = {sp = "LightRed", undercurl = true},
	-- Code
	Title = {fg = "LightGreen", bold = true},
	Todo = {{fg = "Bg2", bg = "Magenta"}, {bold = true}},
	Underlined = {{fg = "Fg3"}, {underline = true}},
	Bold = {bold = true},
	Comment = {{fg = "Fg4"}, {italic = true}},
	Keyword = "Blue",
	Tag = "Keyword",
	Include = "Keyword",
	Boolean = {fg = "Blue", italic = true},
	PreProc = "Cyan",
	Define = "PreProc",
	Statement = "LightBlue",
	Label = "Keyword",
	Exception = "Keyword",
	Special = "Magenta",
	SpecialChar = "Orange",
	Delimiter = "LightRed",
	Operator = "Red",
	String = "Yellow",
	Character = "LightYellow",
	Number = "LightPink",
	Identifier = "Fg1",
	Type = "SlateGrey",
	-- Type = "Fg2",
	TypeDef = {bold = true},
	Function = "Fg1",
	Constant = {fg = "Magenta", italic = true},
	Variable = "Green",

	-- Vim regex syntax
	sqlType = "String",
	sqlOperator = "Operator",

	xmlAttrib = "@attribute",
	xmlEqual = "Operator",
	xmlTag = "Delimiter",
	xmlTagName = "Label",

	DiffAdd = "Green",
	DiffChange = "Cyan",
	DiffDelete = "Red",
	DiffText = "Yellow",

	-- PLUGINS
	DevIconMd = "Fg1",
	-- FzfLua
	FzfLuaBorder = "FloatBorder",
	FzfLuaTitle = "FloatTitle",
	FzfLuaSearch = "Search",
	FzfLuaCursor = {fg = "LightMagenta", bold = true, underline = true},
	FzfLuaCursorLine = {{bg = "BgHi"}, {underline = true}},
	-- Ufo
	UfoFoldedBg = "Bg2",
	UfoFoldedFg = "Fg2",
	UfoFoldedEllipsis = {fg = "LightOrange", bold = true},
	-- LspSignature
	LspSignatureActiveParameter = {bold = true},
	-- Custom
	Neo = {fg = "Cyan", bold = true},
	Vim = {fg = "Green", bold = true},
	Url = {fg = "LightBlue", sp = "LightBlue", underline = true},
}
