return {
	Highlight = "Green",
	LightHighlight = "LightGreen",
	Contrast = "Magenta",
	LightContrast = "LightMagenta",
	-- Basics
	Search = {fg = "LightMagenta", bold = true},
	IncSearch = "Search",
	VertSplit = "Fg6",
	StatusLine = "Bg1",
	StatusLineNC = "Bg2",
	TabLineFill = "",
	TabLineSel = "White",
	Pmenu = "Bg1",
	PmenuSel = "Bg2",
	PmenuSbar = "Bg2",
	PmenuThumb = "Bg3",
	FoldColumn = "Fg1",
	SignColumn = "Fg1",
	Title = {fg = "LightHighlight", bold = true},
	MatchParen = {fg = "LightYellow", italic = true, bold = true},
	ErrorMsg = {fg = "LightRed", bold = true},
	WarningMsg = {fg = "LightOrange", bold = true},
	Question = {fg = "LightYellow", bold = true},
	Error = {sp = "LightRed", undercurl = true},
	Url = {fg = "LightBlue", sp = "LightBlue", underline = true},
	Constant = {fg = "Magenta", italic = true},
	FloatBorder = "Contrast",
	NormalFloat = "Fg1",
	CursorColumn = "Bg1",
	CursorLine = "Bg1",
	LineNr = "Fg5",
	NonText = "Fg7", -- used for listchars (indent)
	SpecialKey = "Orange",
	Keyword = "Blue",
	Include = "Keyword",
	Boolean = "Keyword",
	PreProc = "Cyan",
	Define = "PreProc",
	Statement = "Keyword",
	Special = "Magenta",
	SpecialChar = "Orange",
	Delimiter = "LightRed",
	Operator = "Red",
	Conditional = "LightBlue",
	Command = "LightBlue",
	Repeat = "Command",
	String = "Yellow",
	Character = "LightYellow",
	Number = "LightPink",
	Identifier = "Fg1",
	Type = "Fg1",
	Function = "Fg1",
	Variable = "Green",
	Parameter = "Olive",

	-- Vim syntax highlight changes
	sqlType = "String",
	sqlStatement = "Command",
	sqlOperator = "Operator",

	xmlAttrib = "Parameter",
	xmlEqual = "Operator",
	xmlTag = "Delimiter",
	xmlTagName = "Label",

	DiffAdd = "Green",
	DiffChange = "Cyan",
	DiffDelete = "Red",
	DiffText = "Yellow",
	-- PLUGINS

	i3ConfigCommand = "Command",
	DevIconMd = "Fg1",

	-- FzfLua
	FzfLuaBorder = "FloatBorder",
	FzfLuaTitle = "FloatTitle",
	-- Ufo
	UfoFoldedBg = "Bg1",
	UfoFoldedFg = "Fg2",

	-- Extra
	Neo = {fg = "Cyan", bold = true},
	Vim = {fg = "Green", bold = true},
	FloatTitle = {fg = "Olive", bold = true},
}
