return {
	asciidoctorOption = '@attribute',
	asciidoctorBlockOptions = '@attribute',
	asciidoctorSourceBlock = '@text.literal.block',
	asciidoctorLink = 'Url',
	asciidoctorUrl = 'Url',
	asciidoctorUrlDescription = '@text.reference',
	asciidoctorCode = '@text.literal',
	asciidoctorTitle = '@text.title.1',
	asciidoctorH1 = '@text.title.2',
	asciidoctorH2 = '@text.title.3',
	asciidoctorH3 = '@text.title.4',
	asciidoctorTitleDelimiter = '@text.title.1.marker',
	asciidoctorH1Delimiter = '@text.title.2.marker',
	asciidoctorH2Delimiter = '@text.title.3.marker',
	asciidoctorH3Delimiter = '@text.title.4.marker',
	asciidoctorListContinuation = 'SpecialChar',
}
