return {
	diffAdded = 'DiffAdd',
	diffChanged = 'DiffChange',
	diffDiffer = 'DiffChange',
	diffBDiffer = 'diffDiffer',
	diffRemoved = 'DiffRemove',
	gitcommitSummary = 'Title',
	gitcommitHeader = 'Title',
	gitcommitFile = 'String',
	gitcommitArrow = 'Delimiter',
	gitcommitBranch = 'Green',
	gitcommitType = 'Keyword',
	['@markup.link.gitcommit'] = 'Variable',
	['@markup.heading.gitcommit'] = 'Title',
	['@string.special.url'] = 'File',
}
