return {
	gitrebaseHash = 'Number',
	gitrebaseCommit = 'gitrebaseHash',
	gitrebaseSummary = 'Title',
	gitrebasePick = 'Green',
	gitrebaseEdit = 'Cyan',
	gitrebaseExec = 'LightBlue',
	gitrebaseUpdate = 'Cyan',
	gitrebaseSquash = 'Yellow',
	gitrebaseReword = 'Yellow',
	gitrebaseMerge = 'Yellow',
	gitrebaseFixup = 'Yellow',
	gitrebaseReset = 'LightOrange',
	gitrebaseDrop = 'Red',
	gitrebaseBreak = 'Red',
}
