return {
	helpHeadline = 'Title',
	helpHeader = 'LightGreen',
	helpHyperTextJump = 'Statement',
	helpHyperTextEntry = 'LightMagenta',
	helpCommand = 'String',
	helpTag = '@attribute',
	helpOption = 'Variable',
	helpSpecial = '@attribute',
	helpExample = 'Cyan',
	helpType = 'Keyword',
	helpIdentifier = 'helpType',
	helpFunction = 'LightCyan',
	helpStructure = '@field',
	helpSectionDelim = 'Delimiter',
	helpStorageClass = 'Keyword',
	helpURL = 'Url',
	helpLabel = 'LightMagenta',
	helpException = 'Orange',
	helpTypeDef = 'Keyword',
	helpBar = 'Delimiter',
	helpStar = 'Delimiter',
	helpBackTick = 'Delimiter',
}
