return {
	helpHeadline = "Title",
	helpHeader = "LightGreen",
	helpHyperTextJump = "Command",
	helpHyperTextEntry = "LightMagenta",
	helpCommand = "String",
	helpTag = "Parameter",
	helpOption = "Variable",
	helpSpecial = "Parameter",
	helpExample = "Cyan",
	helpType = "Keyword",
	helpIdentifier = "helpType",
	helpFunction = "LightCyan",
	helpStructure = "@field",
	helpSectionDelim = "Delimiter",
	helpStorageClass = "Keyword",
	helpURL = "Url",
	helpLabel = "LightMagenta",
	helpException = "Orange",
	helpTypeDef = "Keyword",
	helpBar = "Delimiter",
	helpStar = "Delimiter",
	helpBackTick = "Delimiter",
}
