return {
	helpHeadline = 'Title',
	helpHeader = 'LightGreen',
	helpHyperTextJump = 'Statement',
	helpHyperTextEntry = 'Magenta',
	helpCommand = 'String',
	helpTag = '@tag.attribute',
	helpOption = 'Variable',
	helpSpecial = '@attribute',
	helpExample = 'Cyan',
	helpType = 'Keyword',
	helpIdentifier = 'helpType',
	helpFunction = 'LightCyan',
	helpStructure = 'Field',
	helpSectionDelim = 'Delimiter',
	helpStorageClass = 'Keyword',
	helpURL = 'Url',
	helpLabel = 'Magenta',
	helpException = 'LightOrange',
	helpTypeDef = 'Keyword',
	helpBar = 'Delimiter',
	helpStar = 'Delimiter',
	helpBackTick = 'Delimiter',
}
