return {
	mcCommand = "Statement",
	mcXRotation = "Number",
	mcCoordinate = "Number",
	mcCoordinate2 = "Number",
	mcCoordinate3 = "Number",
	mcOp = "Operator",
	mcSelector = "Cyan",
	mcKeyword = "Keyword",
	mcValue = "String",
	mcInt = "Number",
	mcFloat = "Number",
	mcBool = "Boolean",
	mcId = "Constant",
	mcKeyId = "@field",
	mcTag = "String",
	mcObjective = "Variable",
	mcCriteria = "Type",
	mcCriteriaNormal = "mcCriteria",

	mcNBTBracket = "Delimiter",
	mcNBTPath = "@field",
	mcNBTPathDot = "Delimiter",
	mcNBTValue = "String",
	mcNBTQuote = "String",
	mcNBTIndex = "Number",
	mcNBTTagKey = "Variable",
	mcNBTBool = "Boolean",

	mcRangeDots = "Delimiter",
	mcExecuteCond = "Parameter",
	mcExecuteKeyword = "Keyword",
	mcExecuteCondScoreMatch = "mcOp",
	mcExecuteStoreType = "Type",
	mcExecuteStoreWhat = "Parameter",
	mcExecuteStoreWhere = "Type",
	mcExecuteAlignValue = "Parameter",

	mcFilterKeyword = "Parameter",
	mcDataModifyHow = "String",
	mcScoreDisplay = "mcId",
	mcGamerule = "mcId",
	mcFunction = "@field",
	mcXpUnit = "Type",
	mcEnchantLevel = "Number",
}
