return {
	mcCommand = 'Statement',
	mcXRotation = 'Number',
	mcCoordinate = 'Number',
	mcCoordinate2 = 'Number',
	mcCoordinate3 = 'Number',
	mcOp = 'Operator',
	mcSelector = 'Type',
	mcKeyword = 'Keyword',
	mcValue = 'String',
	mcInt = 'Number',
	mcFloat = 'Number',
	mcBool = 'Boolean',
	mcId = 'Constant',
	mcKeyId = 'Field',
	mcTag = 'String',
	mcObjective = 'Variable',
	mcCriteria = 'Type',
	mcCriteriaNormal = 'mcCriteria',

	mcScoreDisplay = 'mcId',
	mcScoreboardPlayers = 'Operator',

	mcNBTBracket = 'Delimiter',
	mcNBTPath = 'Field',
	mcNBTPathDot = 'Delimiter',
	mcNBTValue = 'String',
	mcNBTQuote = 'String',
	mcNBTIndex = 'Number',
	mcNBTTagKey = 'Variable',
	mcNBTBool = 'Boolean',

	mcExecuteCond = 'Parameter',
	mcExecuteKeyword = 'Keyword',
	mcExecuteCondScoreMatch = 'mcOp',
	mcExecuteStoreType = 'Type',
	mcExecuteStoreWhat = 'mcExecuteCond',
	mcExecuteStoreWhere = 'Type',
	mcExecuteAlignValue = 'Parameter',

	mcTagKeyword = 'Operator',
	mcRangeDots = 'Delimiter',
	mcFilterKeyword = 'Parameter',
	mcFilterSort = 'Constant',
	mcDataModifyHow = 'Operator',
	mcGamerule = 'mcId',
	mcFunction = 'Field',
	mcXpUnit = 'Type',
	mcEnchantLevel = 'Number',
	mcEBSDataModify = 'mcExecuteCond',
}
